# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantID', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=256)),
                ('realPathTotalSum', models.FloatField()),
                ('expectedPathTotalSum', models.FloatField()),
                ('surFacingStepTotalCost', models.FloatField()),
                ('riskTotalCost', models.FloatField()),
                ('wayPointTotalCost', models.FloatField()),
                ('riskBudget', models.FloatField()),
                ('surfacingStepBudget', models.FloatField()),
                ('canvasScale', models.FloatField()),
                ('canvasBias', models.FloatField()),
                ('collisionDetectionPrecision', models.FloatField()),
                ('chosenMapName', models.CharField(max_length=256)),
                ('chonsenMapCoordinates', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
